# lb1 service
kind: Service
apiVersion: v1
metadata:
  name: lb1-service
spec:
  selector:
    app: lb1-service
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb1-service-deployment
  labels:
    app: lb1-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb1-service
  template:
    metadata:
      labels:
        app: lb1-service
    spec:
      containers:
      - name: lb1-service
        image: jiashenc/sysml-demo:yolo-amd64
        command: ["python"]
        args: ["-m", "service.generic_server", "yolo.demo.lb1_service"]
        ports:
        - containerPort: 8080
---
# lb2 service
kind: Service
apiVersion: v1
metadata:
  name: lb2-service
spec:
  selector:
    app: lb2-service
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb2-service-deployment
  labels:
    app: lb2-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb2-service
  template:
    metadata:
      labels:
        app: lb2-service
    spec:
      containers:
      - name: lb2-service
        image: jiashenc/sysml-demo:yolo-amd64
        command: ["python"]
        args: ["-m", "service.generic_server", "yolo.demo.lb2_service"]
        ports:
        - containerPort: 8080
---
# bounding box service
kind: Service
apiVersion: v1
metadata:
  name: bb-service
spec:
  selector:
    app: bb-service
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-service-deployment
  labels:
    app: bb-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-service
  template:
    metadata:
      labels:
        app: bb-service
    spec:
      containers:
      - name: bb-service
        image: jiashenc/sysml-demo:yolo-amd64
        command: ["python"]
        args: ["-m", "service.generic_server", "yolo.demo.bb_service"]
        ports:
        - containerPort: 8080